# Copyright (c) 2024. All rights reserved.
# author: Dennis Grewe
version: '3'

  # golfclub management container to add,
  # update, delete golfcourse entities from/to
  # the data base
  golfclub-management:
    build:
      context: ../golfclub-management
    container_name: springboot
    volumes:
      - ../golfclub-management:/workspace
    ports:
      - "8080:8080"
    environment:
      - JAVA_HOME=/docker-java-home
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

# define a local bridge network
# to allow containers to discover
# and interact with each other
networks:
  app-network:
    driver: bridge